version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
  postgres_db:
    image: postgres
    ports:
      -"5432:5432"
    environment:
      - DB_HOST=localhost
      - DB_USER=mytodo
      - DB_PASSWORD=todopassword
      - DB_NAME=todo

  postgres:
    image: postgres:14
    restart: always
    environment:
      - MYPOSGRES_ROOT_PASSWORD=todopassword
      - MYPOSTGRES_DATABASE=todo
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: